### ISSUE TITLE
show png or jpg image as background

### ISSUE THREAD

**Issue by rajesh-vi** [crisbeto/angular-svg-round-progressbar#101]
How to show png or jpg image as background of circular progress bar? is there any option to do it?

**Comment by crisbeto** [comment]
There's no built-in option, but it's easy to do with CSS:

```css
.round-progress {
  background: url(<link to your image>);
  border-radius: 100%;
}
```
