### ISSUE TITLE
Img background

### ISSUE THREAD

**Issue by wuilmerj24** [crisbeto/angular-svg-round-progressbar#174]
how to place the image at the bottom of the circle

similar to this
![octopus_step3](https://user-images.githubusercontent.com/7539995/47946915-ba091c80-dee0-11e8-9e9d-1c769cb02ecd.jpg)

**Comment by wuilmerj24** [comment]
Ping

**Comment by crisbeto** [comment]
@wuilmerj24 you should be able to get the same result by setting a background image on the `round-progress` element:

```css
round-progress {
  background-image: url(./path-to-image);
  border-radius: 100%;
}
```
