### ISSUE TITLE
Add text in middle

### ISSUE THREAD

**Issue by warapitiya** [crisbeto/angular-svg-round-progressbar#27]
How can I add a text in middle of the cycle saying 50% or any...

**Comment by warapitiya** [comment]
Adding this css helped me. thanks for awesome directive :dancers: 

```css
.progress{
    position: absolute;
    width: 100%;
    height: 100%;
    line-height: 6em;
    font-size:1em;
    text-align: center;
    color: #886aea;
    font-weight: 100;
}
```
