### ISSUE TITLE
How can I put picture inside the round progressbar?

### ISSUE THREAD

**Issue by KimCrab** [crisbeto/angular-svg-round-progressbar#34]
Is it possible to put picture inside the round progressbar? and I want to know how do you implemente clock example.

**Comment by crisbeto** [comment]
1. You can see how the clock example is implemented in the demo's source here: https://github.com/crisbeto/angular-svg-round-progressbar/blob/master/build/index.html#L262
2. You can put an image inside the circle with CSS:

```css
.round-progress {
    background: url(YourImageHere.png);
    border-radius: 1000px; /* so the image doesn't overflow */
    overflow: hidden;
}
```
