### ISSUE TITLE
Set the fill color of the circle.

### ISSUE THREAD

**Issue by Slavrix** [crisbeto/angular-svg-round-progressbar#53]
I could see that there are options to be able to colour the stroke, and the background of the stroke but there isn't any option to fill the circle.
Or have I missed something.

**Comment by crisbeto** [comment]
Nope, it's not through the options. You can do it with CSS though, for example:

```css
.round-progress circle{
  fill: #f00;
}
```
